---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: server1
    run_list:
      - recipe[openldap_mm::default]
    driver_config:
      network:
        - ["forwarded_port", {guest: 389, host: 1389}]
        - ['private_network', {ip: '192.168.33.33'}]
    attributes:
      openldap_mm:
        server1: "192.168.33.33"
        server2: "192.168.33.34"
  - name: server2
    run_list:
      - recipe[openldap_mm::default]
    driver_config:
      network:
        - ["forwarded_port", {guest: 389, host: 2389}]
        - ['private_network', {ip: '192.168.33.34'}]
    attributes:
      openldap_mm:
        server1: "192.168.33.33"
        server2: "192.168.33.34"