---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 389, host: 1389}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[openldap_mm::server]
    attributes:
