AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Max: 250

HashSyntax:
  EnforcedStyle: ruby19

Documentation:
  Enabled: false

CyclomaticComplexity:
  Max: 12

Style/NumericLiterals:
  Enabled: false
